package com.capgemini.menuapp.model

import com.google.gson.annotations.SerializedName

data class Product(
    @SerializedName("ID")
    val ID: Int,
    @SerializedName("TypeID")
    val TypeID: Int,
    @SerializedName("MenuTypeID")
    val MenuTypeID: Int,
    @SerializedName("Names")
    val Names: Array<String>,
    @SerializedName("Categories")
    val Categories: Array<String>,
    @SerializedName("Recipe")
    val Recipe: Recipe
)

//Autogenerated functions to get equality
{
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Product

        if (ID != other.ID) return false
        if (TypeID != other.TypeID) return false
        if (MenuTypeID != other.MenuTypeID) return false
        if (!Names.contentEquals(other.Names)) return false
        if (!Categories.contentEquals(other.Categories)) return false
        if (Recipe != other.Recipe) return false

        return true
    }

    override fun hashCode(): Int {
        var result = ID
        result = 31 * result + TypeID
        result = 31 * result + MenuTypeID
        result = 31 * result + Names.contentHashCode()
        result = 31 * result + Categories.contentHashCode()
        result = 31 * result + Recipe.hashCode()
        return result
    }
}