package com.capgemini.menuapp.model

import com.google.gson.annotations.SerializedName

data class Recipe(
    @SerializedName("RecipeID")
    val id: Int,
    @SerializedName("Ingredients")
    val ingredients: Array<Ingredient>
)

//Autogenerated functions so it can get equality
{
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Recipe

        if (id != other.id) return false
        if (!ingredients.contentEquals(other.ingredients)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id
        result = 31 * result + ingredients.contentHashCode()
        return result
    }
}