package com.capgemini.menuapp.model

import com.google.gson.annotations.SerializedName

data class Recipe(
    @SerializedName("ID")
    val ID: Int,
    @SerializedName("Ingredients")
    val Ingredients: Array<Ingredient>
)

//Autogenerated functions so it can get equality
{
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Recipe

        if (ID != other.ID) return false
        if (!Ingredients.contentEquals(other.Ingredients)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = ID
        result = 31 * result + Ingredients.contentHashCode()
        return result
    }
}